<?php

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_left-navigation-menu',
        'title' => 'Left Navigation Menu',
        'fields' => array (
            array (
                'key' => 'field_52e04d925f72e',
                'label' => 'Title',
                'name' => 'left_nav_menu_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_52e7f22d0203f',
                'label' => 'Hide?',
                'name' => 'hide_in_left_nav',
                'type' => 'true_false',
                'message' => '',
                'default_value' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'custom_fields',
                1 => 'discussion',
                2 => 'comments',
                3 => 'format',
                4 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_right-sidebars',
        'title' => 'Right Sidebars',
        'fields' => array (
            array (
                'key' => 'field_5273d86c7161b',
                'label' => 'Right Sidebars',
                'name' => 'sidebars',
                'type' => 'flexible_content',
                'layouts' => array (
                    array (
                        'label' => 'Related Links',
                        'name' => 'links',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_5273d9187161c',
                                'label' => 'Sidebar Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_530fa3ded05cc',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_5273d9887161d',
                                'label' => 'Links',
                                'name' => 'links',
                                'type' => 'repeater',
                                'column_width' => '',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5273d9c17161e',
                                        'label' => 'Link Text',
                                        'name' => 'link_text',
                                        'type' => 'text',
                                        'required' => 1,
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5273d9d67161f',
                                        'label' => 'URL',
                                        'name' => 'url',
                                        'type' => 'text',
                                        'required' => 1,
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'none',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_530fa4edd05cd',
                                        'label' => 'Description',
                                        'name' => 'description',
                                        'type' => 'text',
                                        'column_width' => '',
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'formatting' => 'html',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5273da3271620',
                                        'label' => 'Open in New Window',
                                        'name' => 'open_in_new_window',
                                        'type' => 'true_false',
                                        'column_width' => '',
                                        'message' => '',
                                        'default_value' => 1,
                                    ),
                                ),
                                'row_min' => '',
                                'row_limit' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Link',
                            ),
                        ),
                    ),
                    array (
                        'label' => 'Image & Text',
                        'name' => 'image_&_text',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_530fb7c1944d5',
                                'label' => 'Image',
                                'name' => 'image',
                                'type' => 'image',
                                'column_width' => '',
                                'save_format' => 'id',
                                'preview_size' => 'medium',
                                'library' => 'all',
                            ),
                            array (
                                'key' => 'field_530fba90944d6',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_530fbaa2944d7',
                                'label' => 'Text',
                                'name' => 'text',
                                'type' => 'wysiwyg',
                                'column_width' => '',
                                'default_value' => '',
                                'toolbar' => 'full',
                                'media_upload' => 'no',
                            ),
                            array (
                                'key' => 'field_530fbad4944d8',
                                'label' => 'Link Text',
                                'name' => 'link_text',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_530fbb25944d9',
                                'label' => 'URL',
                                'name' => 'url',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_530fbb37944da',
                                'label' => 'Open in New Window',
                                'name' => 'open_in_new_window',
                                'type' => 'true_false',
                                'column_width' => '',
                                'message' => '',
                                'default_value' => 1,
                            ),
                        ),
                    ),
                ),
                'button_label' => 'Add Sidebar',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));

    register_field_group(array (
        'id' => 'acf_slide',
        'title' => 'Slide',
        'fields' => array (
            array (
                'key' => 'field_53ada62a49e92',
                'label' => 'Slide Image',
                'name' => 'image',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array (
                'key' => 'field_53ada65949e93',
                'label' => 'Slide Caption',
                'name' => 'caption',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_53adb8f450fc8',
                'label' => 'Link URL',
                'name' => 'link_url',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'slider',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array (
        'id' => 'acf_metrics',
        'title' => 'Metrics',
        'fields' => array (
            array (
                'key' => 'field_53baac6ccf542',
                'label' => 'Chart Image',
                'name' => 'image',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'chart',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'charts',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'acf_after_title',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'tags',
                12 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array (
        'id' => 'acf_hrpo-on-demand-topics',
        'title' => 'HRPO On Demand Topics',
        'fields' => array (
            array (
                'key' => 'field_5432c03289116',
                'label' => 'Topic',
                'name' => 'topic',
                'type' => 'repeater',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5432c05f89117',
                        'label' => 'Title',
                        'name' => 'title',
                        'type' => 'text',
                        'required' => 1,
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'none',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5432c1e389118',
                        'label' => 'Description',
                        'name' => 'description',
                        'type' => 'textarea',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'formatting' => 'br',
                    ),
                    array (
                        'key' => 'field_5432c1f989119',
                        'label' => 'Email Link',
                        'name' => 'email_link',
                        'type' => 'email',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
                'row_min' => '',
                'row_limit' => '',
                'layout' => 'table',
                'button_label' => 'Add Topic',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '162',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));

    register_field_group(array (
        'id' => 'acf_staff-directory',
        'title' => 'Staff Directory',
        'fields' => array (
            array (
                'key' => 'field_543408d2dbd5d',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5433f5e387368',
                'label' => 'Phone',
                'name' => 'phone',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5433f5f487369',
                'label' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'staff',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'permalink',
                1 => 'the_content',
                2 => 'excerpt',
                3 => 'custom_fields',
                4 => 'discussion',
                5 => 'comments',
                6 => 'revisions',
                7 => 'slug',
                8 => 'author',
                9 => 'format',
                10 => 'featured_image',
                11 => 'categories',
                12 => 'tags',
                13 => 'send-trackbacks',
            ),
        ),
        'menu_order' => 0,
    ));

}
